"""Structured, UI-facing views of deterministic dataframe executions.

This module deliberately reads execution data, never formatted Korean answer
text.  It is kept independent from FastAPI so direct callers can test it.
"""
from __future__ import annotations

from hashlib import sha256
import re
from typing import Any

import pandas as pd

from pandas_engine.query_executor import QueryExecutionResult
from utils.semantic_schema import SYSTEM_COLUMNS, infer_column_meaning
from utils.table_parser import IDENTITY_INTERNAL_COLS

_PRIVATE = {"contact", "email", "phone"}
_PRESENTATION_INTERNAL_COLUMNS = {"source", "표시명", "엔티티 타입", "entity_type", "row"}
_INTERNAL_COLUMNS = set(SYSTEM_COLUMNS) | set(IDENTITY_INTERNAL_COLS) | _PRESENTATION_INTERNAL_COLUMNS
_DETAILS: dict[str, dict[str, Any]] = {}


def _is_processing_column(key: str) -> bool:
    """Return whether a parser/OCR-produced field must stay out of the UI."""
    compact = re.sub(r"[\s_-]+", "", key).casefold()
    return compact.startswith("ocr")


def get_interactive_detail(reference: str, *, offset: int = 0, limit: int = 50) -> dict[str, Any] | None:
    """Read an in-memory detail generated by this process; never log values."""
    detail = _DETAILS.get(reference)
    if detail is None:
        return None
    if detail.get("kind") != "calculation_detail":
        return detail
    all_contributors = detail.get("_all_contributors", [])
    page_items = all_contributors[offset:offset + limit]
    return {
        **{key: value for key, value in detail.items() if key != "_all_contributors"},
        "contributors": page_items,
        "page": {
            "offset": offset, "limit": limit, "total": len(all_contributors),
            "has_more": offset + len(page_items) < len(all_contributors),
        },
    }


def _json_value(value: Any) -> Any:
    if value is None or pd.isna(value):
        return None
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if hasattr(value, "item"):
        return value.item()
    return value


def _row_identity(row: pd.Series) -> dict[str, str]:
    return {
        "document_id": str(row.get("__document_id", "")),
        "table_id": str(row.get("__table_id", "")),
        "row_id": str(row.get("__row_id", "")),
    }


def _person_identity_seed(row: pd.Series, name_column: str) -> tuple[str, str]:
    """Prefer ingest identity, then schema-detected contact data, then scoped display name."""
    candidate = str(row.get("person_candidate_key", "")).strip()
    if candidate and candidate.lower() not in {"nan", "none", "null"}:
        return candidate, "candidate_key"
    contact_parts: list[str] = []
    for column in row.index:
        meaning = infer_column_meaning(str(column), pd.Series([row[column]]))
        value = _json_value(row[column])
        if value is not None and (
            meaning.qualifier == "contact"
            or meaning.pii_type in {"phone_number", "email_address"}
        ):
            contact_parts.append(f"{column}={value}")
    if contact_parts:
        return "|".join(sorted(contact_parts)), "contact_scoped"
    return str(row[name_column]).strip(), "display_name_scoped"


def _is_visible_column(column: object, series: pd.Series, *, include_contact: bool) -> bool:
    key = str(column)
    # Parsing, OCR, identity and semantic-enrichment fields never belong in a
    # user-facing card.  Source table columns do not use the reserved `_` prefix.
    if key in _INTERNAL_COLUMNS or key.startswith("_") or _is_processing_column(key):
        return False
    meaning = infer_column_meaning(key, series)
    if meaning.concept == "quality" or meaning.is_derived:
        return False
    if not include_contact and (
        meaning.qualifier == "contact"
        or meaning.pii_type in {"phone_number", "email_address"}
    ):
        return False
    return True


def _payment_history_for_row(row: pd.Series, name_column: str) -> dict[str, Any] | None:
    fields: list[dict[str, Any]] = []
    has_money = False
    for column in row.index:
        key = str(column)
        if key == name_column or not _is_visible_column(key, pd.Series([row[column]]), include_contact=False):
            continue
        meaning = infer_column_meaning(key, pd.Series([row[column]]))
        if meaning.data_type == "money" or meaning.concept == "temporal" or meaning.role == "category":
            value = _json_value(row[column])
            fields.append({"column": key, "value": value, "data_type": meaning.data_type, "role": meaning.role})
            has_money = has_money or meaning.data_type == "money"
    return {"fields": fields} if has_money else None


def _entity_for_row(row: pd.Series) -> dict[str, Any] | None:
    name_column = next(
        (
            str(column) for column in row.index
            if _is_visible_column(column, pd.Series([row[column]]), include_contact=True)
            and infer_column_meaning(str(column), pd.Series([row[column]])).role == "entity_name"
            and infer_column_meaning(str(column), pd.Series([row[column]])).qualifier == "person"
        ),
        None,
    )
    if not name_column or _json_value(row[name_column]) is None:
        return None
    identity = _row_identity(row)
    person_seed, strategy = _person_identity_seed(row, name_column)
    raw = "|".join((identity["document_id"], identity["table_id"], person_seed))
    entity_id = "ent_" + sha256(raw.encode("utf-8")).hexdigest()[:20]
    attributes: list[dict[str, Any]] = []
    detail_attributes: list[dict[str, Any]] = []
    for column in row.index:
        key = str(column)
        if key == name_column or not _is_visible_column(key, pd.Series([row[column]]), include_contact=True):
            continue
        meaning = infer_column_meaning(key, pd.Series([row[column]]))
        value = _json_value(row[column])
        attribute = {"column": key, "role": meaning.role, "value": value, "missing": value is None}
        detail_attributes.append(attribute)
        if meaning.qualifier != "contact" and meaning.pii_type not in {"phone_number", "email_address"}:
            attributes.append(attribute)
    history = _payment_history_for_row(row, name_column)
    existing_detail = _DETAILS.get(entity_id)
    payment_history = list(existing_detail.get("payment_history", [])) if existing_detail else []
    if history is not None and history not in payment_history:
        payment_history.append(history)
    _DETAILS[entity_id] = {
        "version": "1", "kind": "entity_detail", "entity_id": entity_id,
        "display_name": str(row[name_column]), "identity": identity,
        "attributes": existing_detail.get("attributes", detail_attributes) if existing_detail else detail_attributes,
        "payment_history": payment_history,
    }
    return {
        "entity_id": entity_id,
        "entity_type": "person",
        "display_name": str(row[name_column]),
        "identity": {**identity, "strategy": strategy},
        "attributes": attributes,
        "detail_ref": entity_id,
    }


def _inline_segments(answer: str, entities: list[dict[str, Any]], calculation: dict[str, Any] | None) -> list[dict[str, Any]]:
    """Create UI annotations from structured execution values, not browser text parsing."""
    display_answer = answer.split("\n\n계산 근거:", 1)[0]
    actions: list[tuple[str, dict[str, Any]]] = []
    by_name: dict[str, list[dict[str, Any]]] = {}
    for entity in entities:
        by_name.setdefault(entity["display_name"], []).append(entity)
    for name, matches in by_name.items():
        if len(matches) == 1:
            actions.append((name, {"kind": "entity", "detail_ref": matches[0]["detail_ref"]}))
        elif matches:
            collection_id = "ents_" + sha256("|".join(sorted(item["entity_id"] for item in matches)).encode("utf-8")).hexdigest()[:20]
            _DETAILS[collection_id] = {
                "version": "1", "kind": "entity_collection_detail",
                "display_name": name,
                "candidates": [
                    {"entity_id": item["entity_id"], "detail_ref": item["detail_ref"], "attributes": item["attributes"]}
                    for item in matches
                ],
            }
            actions.append((name, {"kind": "entity", "detail_ref": collection_id}))
    if calculation and calculation.get("value") is not None:
        value = calculation["value"]
        try:
            formatted = f"{float(value):,.0f}" if float(value).is_integer() else f"{float(value):,.2f}".rstrip("0").rstrip(".")
        except (TypeError, ValueError):
            formatted = str(value)
        suffix = "원" if calculation.get("target", {}).get("data_type") == "money" else ""
        actions.append((formatted + suffix, {"kind": "calculation", "detail_ref": calculation["detail_ref"]}))
        actions.append((formatted, {"kind": "calculation", "detail_ref": calculation["detail_ref"]}))
    actions.sort(key=lambda item: len(item[0]), reverse=True)
    segments: list[dict[str, Any]] = []
    cursor = 0
    while cursor < len(display_answer):
        match = next(((text, action) for text, action in actions if display_answer.startswith(text, cursor)), None)
        if match:
            text, action = match
            segments.append({"text": text, **action})
            cursor += len(text)
        else:
            start = cursor
            cursor += 1
            while cursor < len(display_answer) and not any(display_answer.startswith(text, cursor) for text, _ in actions):
                cursor += 1
            segments.append({"text": display_answer[start:cursor]})
    return segments


def build_interactive_result(result: QueryExecutionResult, *, page_size: int = 50, answer: str | None = None) -> dict[str, Any]:
    """Return a bounded JSON-safe result contract for the current execution."""
    frame = result.value if isinstance(result.value, pd.DataFrame) else result.matched_frame
    records: list[dict[str, Any]] = []
    entities: list[dict[str, Any]] = []
    if isinstance(frame, pd.DataFrame):
        for _, row in frame.head(page_size).iterrows():
            records.append({
                str(k): _json_value(v)
                for k, v in row.items()
                if _is_visible_column(k, pd.Series([v]), include_contact=False)
            })
    # Projection intentionally removes system columns from list values.  Build
    # entities from the matching execution rows so references retain row scope.
    entity_frame = result.matched_frame
    inline_entities: list[dict[str, Any]] = []
    if isinstance(entity_frame, pd.DataFrame):
        seen_entity_ids: set[str] = set()
        for _, row in entity_frame.iterrows():
            entity = _entity_for_row(row)
            if entity and entity["entity_id"] not in seen_entity_ids:
                seen_entity_ids.add(entity["entity_id"])
                inline_entities.append(entity)
        entities = inline_entities[:page_size]
    total = int(len(frame)) if isinstance(frame, pd.DataFrame) else 0
    calculation = None
    if result.operation in {"sum", "mean", "median", "mode", "min", "max", "count", "group_sum"}:
        calculation_id = "calc_" + sha256((result.source_file + result.operation + str(result.target)).encode()).hexdigest()[:20]
        contributors = [
            {
                str(k): _json_value(v)
                for k, v in row.items()
                if _is_visible_column(k, pd.Series([v]), include_contact=False)
            }
            for _, row in result.matched_frame.iterrows()
        ]
        _DETAILS[calculation_id] = {
            "version": "1", "kind": "calculation_detail", "calculation_id": calculation_id,
            "operation": result.operation,
            "target": result.target,
            "value": _json_value(result.value) if not isinstance(result.value, pd.DataFrame) else None,
            "valid_rows": result.valid_rows,
            "excluded_rows": result.excluded_rows,
            "_all_contributors": contributors,
        }
        calculation = {
            "calculation_id": calculation_id,
            "operation": result.operation,
            "target": {"column": result.target, "data_type": result.target_data_type},
            "value": _json_value(result.value) if not isinstance(result.value, pd.DataFrame) else None,
            "counts": {"source_rows": result.evidence.source_rows, "filtered_rows": result.evidence.filtered_rows, "valid_rows": result.valid_rows, "excluded_rows": result.excluded_rows},
            "detail_ref": calculation_id,
        }
        if result.operation == "mean" and result.value is not None:
            calculation["formula"] = {"numerator": _json_value(result.value * result.valid_rows), "denominator": result.valid_rows}
    payload = {
        "version": "1",
        "kind": "records" if isinstance(result.value, pd.DataFrame) else "scalar",
        "operation": result.operation,
        "records": records,
        "entities": entities,
        "calculation": calculation,
        "page": {"offset": 0, "limit": page_size, "total": total, "has_more": total > page_size} if isinstance(frame, pd.DataFrame) else None,
    }
    if answer is not None:
        payload["inline_segments"] = _inline_segments(answer, inline_entities, calculation)
    return payload


def build_interactive_dataframe(frame: pd.DataFrame, *, page_size: int = 50, answer: str | None = None) -> dict[str, Any]:
    """Structured view for verified legacy/direct dataframe queries."""
    visible = frame[[
        column for column in frame.columns
        if _is_visible_column(column, frame[column], include_contact=False)
    ]]
    records = [
        {str(k): _json_value(v) for k, v in row.items()}
        for _, row in visible.head(page_size).iterrows()
    ]
    inline_entities = []
    seen_entity_ids: set[str] = set()
    for _, row in frame.iterrows():
        entity = _entity_for_row(row)
        if entity and entity["entity_id"] not in seen_entity_ids:
            seen_entity_ids.add(entity["entity_id"])
            inline_entities.append(entity)
    entities = inline_entities[:page_size]
    payload = {
        "version": "1", "kind": "records", "operation": "list",
        "records": records, "entities": entities, "calculation": None,
        "page": {"offset": 0, "limit": page_size, "total": int(len(frame)), "has_more": len(frame) > page_size},
    }
    if answer is not None:
        payload["inline_segments"] = _inline_segments(answer, inline_entities, None)
    return payload
